// messages here validation messages 3rd party url
const messages = {
    validation: {
        TOKEN_EXPIRE: "Token Expired, Please login again!",
        INVALID_TOKEN: "Invalid token.",
        TOKEN_NOT_AVAILABLE: "Access denied. No token provided.",
        SESSION_NOT_AVAILABLE: "Session Expired, Please login again!",
        ACCESS_NOT_AVAILABLE: "You don't have access to perform this activity.",
    },
    alert: {
        CRED_MSG: "Invalid Credential!",
        CRED_NOT_MATCH: "New Password and Confirm Password didn't match!",
        SAME_CRED: "Current Password and New Password is Same!",
        OTP_INVALID: "OTP is Invalid!",
        OTP_VALID: "OTP Verified Successfully!",
        OTP_SENT: "OTP Sent Successfully!",
        Data_NOT_FOUND: "Data Not Found",
        SERVER_MSG: "Something went wrong!",
        SUCCESS_LOGIN: "Login Successfull!",
        ACCOUNT_STATUS_ERR: "Sorry! Your account is InActive!",
        SERVER_LOGIN_ERR: "Unable to Login!",
        PASSWORD_REQUIRED: "Password is required!",
        SUCCESS_LOGOUT: "Logout Successfull!",
        SUCCESS_GET_DATA: "Data fetched successfully!",
        SUCCESS_SAVE_DATA: "Data saved successfully!",
        SUCCESS_UPDATE_DATA: "Data updated successfully!",
        SUCCESS_DELETE_DATA: "Data deleted successfully!",
        MRF_TYPE_ERR: "Type is not valid!",
        MRF_HIERARCHY_ERR: "MRF Hierarchy is not available for your department",
        MRF_ALREADY_SUBMITTED: "MRF Already Submitted",
        MRF_ACTION: "MRF Action has been performed",
        ONBOARDING_TYPE_ERR: "Onboarding Stage is not valid",
        POLICY_NOT_FOUND: "Policy Not Found",
        INTERVIEW_STATUS: "Interview Status is Required!",
        LEAVE_BALANCE_NO_AVAILABLE: "No leave balance available",
        LEAVE_HIERARCHY_ERR: "LEAVE Hierarchy is not available for your department",
        LEAVE_ACTION: "Action has been performed",
        DEFAULT_SHIFT_NA: "Default Shift Not Available",
        VALID_EXPRESSION: "Valid Expression",
        INVALID_EXPRESSION: "Invalid Expression",
        IMAGE_SAVE_FAILED: "Failed to save image",
        FILE_NOT_FOUND: "File Not Found",
        INVALID_FILE: "Invalid file format. Only Excel file is allowed",
        EMPLOYEE_ID: "Employee not found",
        EFFECTIVE_DATE: "Effective date must be greater than current date",
        CREATE_POST_MSG: "Post content or file is required",
        POST_LIKE: "Post Liked Successfully",
        POST_DISLIKE: "Like Revoked Successfully",
        POST_COMMENT: "Comment Added Successfully",
        VALID_CTC: "Please Input Valid CTC Value",
        TEMPLATE_NAME_EXIST: "Template Name Already Exist",
        SELECT_EMPLOYEE: "Please Select Employees",
        ARREAR_STATUS: 'This Month arrears Already Exist',
        PAY_SCHEDULE_ERROR: 'Pay Scheduler Not Found ',
        THIS_MONTH_APPROVAL_ALREADY:"pay run approval already",
        ATTENDANCE_LOCK_ERROR: "Attendance Already locked for this month",
        ADD_LOCATION_SUCCESS: "Location saved successfully!",
        HIERARCHY_ERR:"Hierarchy is not available",
        TRAVEL_ID_NOT_FOUND:"Travel Id Not Found",
        ASSIGN_SUCCESS:'Assign Successfully',
        FUNCTION_ALREADY_ASSIGNED:"This Function already Assigned.",
        RATING_FIRST:"Please give rating first",
        FINANCIAL_YEAR_NOT_FOUND:"Financial year not found",
        PARAMETER_WEIGHAGE_EXCEEDED:"Parameter Weightage Limit Exceeded",
        SUB_PARAMETER_WEIGHAGE_EXCEEDED:"Sub Parameter Weightage Limit Exceeded",
        PARAMETER_NOT_FOUND:"Parameter Not Found",
        PLEASE_SELECT:"Please Select Leave type and Dates",
        EMAIL_ALREADY_EXISTS:"Email Already Exists",
        ADMIN_CREATED:"Admin Created",
        USER_NOT_FOUND:"User not found",
        SALARY_NOT_FOUND:"Salary data not found",
        SHIFT_CODE_ALREADY:"Shift Code already exists.",
        ID_NOT_FOUND:"Employee id Not found"
    },
};

const generateArray = () => {
    const array = [];
    for (let i = 1; i <= 30; i++) {
        array.push({ id: i, label: `${i}`, value: i });
    }
    return array;
}
const generateArrays = generateArray()

const otpExpiresIn = {
    value: 3,
    type: 'minutes',  //minutes or hours or days
};

const appConstants = {
    gender: [
        { id: 1, label: "Male", value: "Male" },
        { id: 2, label: "Female", value: "Female" },
        { id: 3, label: "Other", value: "Other" }
    ],
    accountStatus: [
        { id: 1, label: 'Active', value: 'active' },
        { id: 2, label: 'Inactive', value: 'inactive' },
    ],
    month: [
        { id: 1, label: 'One', value: '1' },
        { id: 2, label: 'Two', value: '2' },
        { id: 3, label: 'Three', value: '3' },
        { id: 4, label: 'Four', value: '4' },
        { id: 5, label: 'Five', value: '5' },
        { id: 6, label: 'Six', value: '6' },
        { id: 7, label: 'Seven', value: '7' },
        { id: 8, label: 'Eight', value: '8' },
        { id: 9, label: 'Nine', value: '9' },
        { id: 10, label: 'Ten', value: '10' },
        { id: 11, label: 'Eleven', value: '11' },
        { id: 12, label: 'Twelve', value: '12' },
    ],
    bloodGroup: [
        { id: 1, label: 'O+', value: 'O+' },
        { id: 2, label: 'O-', value: 'O-' },
        { id: 3, label: 'A+', value: 'A+' },
        { id: 4, label: 'A-', value: 'A-' },
        { id: 5, label: 'B+', value: 'B+' },
        { id: 6, label: 'B-', value: 'B-' },
        { id: 7, label: 'AB+', value: 'AB+' },
        { id: 8, label: 'AB-', value: 'AB-' },
    ],
    maritalStatus: [
        { id: 1, label: 'Single', value: 'Single' },
        { id: 2, label: 'Married', value: 'Married' },
    ],
    dayType: [
        { label: 'Full Day', value: 'Full Day' },
        { label: 'First Half Day', value: 'First Half Day' },
        { label: 'Second Half Day', value: 'Second Half Day' },
    ],
    workingDays: [
        { id: 1, label: '20', value: 20 },
        { id: 2, label: '21', value: 21 },
        { id: 3, label: '22', value: 22 },
        { id: 4, label: '23', value: 23 },
        { id: 5, label: '24', value: 24 },
        { id: 6, label: '25', value: 25 },
        { id: 7, label: '26', value: 26 },
        { id: 8, label: '27', value: 27 },
        { id: 9, label: '28', value: 28 },
        { id: 10, label: '29', value: 29 },
        { id: 11, label: '30', value: 30 },
    ],
    monthDays: generateArrays,
}

const leaveConstants = {
    expiresOn: [
        { id: 1, label: 'Yearly', value: 'yearly' },
        { id: 2, label: 'Financial year', value: 'financial_year' },
        { id: 3, label: 'Half yearly', value: 'half_yearly' },
        { id: 4, label: 'Quarterly', value: 'quarterly' },
        { id: 5, label: 'Monthly', value: 'monthly' },
        { id: 5, label: 'Weekly', value: 'weekly' },
    ],
    leaveUnit: [
        { id: 1, label: 'Days', value: 'days' },
        { id: 2, label: 'Hours', value: 'hours' },
    ],
    presentStatus: [
        { id: 1, label: 'PR', value: 'PR' },
        { id: 2, label: 'AB', value: 'AB' },
        { id: 3, label: 'FHP', value: 'FHP' },
        { id: 4, label: 'SHP', value: 'SHP' },
        { id: 5, label: 'WO', value: 'WO' },
        { id: 6, label: 'WO_P', value: 'WO_P' },
        { id: 7, label: 'WO_FHP', value: 'WO_FHP' },
        { id: 8, label: 'WO_SHP', value: 'WO_SHP' },
        { id: 9, label: 'PH', value: 'PH' },
        { id: 10, label: 'PH_P', value: 'PH_P' },
        { id: 11, label: 'PH_FHP', value: 'PH_FHP' },
        { id: 12, label: 'PH_SHP', value: 'PH_SHP' },
        { id: 13, label: 'PL', value: 'PL' },
        { id: 14, label: 'CL', value: 'CL' },
        { id: 15, label: 'SL', value: 'SL' },
        { id: 16, label: 'EL', value: 'EL' },
        { id: 17, label: 'WL', value: 'WL' },
        { id: 18, label: 'LW', value: 'LW' },
    ],
    inOutData: [
        { label: "IN", value: "IN" },
        { label: "OUT", value: "OUT" },
    ],

    activityData: [
        { label: "Main Gate IN", value: "main_gate_in" },
        { label: "Main Gate Out", value: "main_gate_out" },
        { label: "Cafe In", value: "cafe_in" },
        { label: "Cafe Out", value: "cafe_out", },
    ],
    leaveCreditBasis: [
        { id: 1, label: 'Attendance lock', value: 'attendance_lock' },
        { id: 2, label: 'First day of month', value: 'first_day_of_month' },
        { id: 3, label: 'Last day of month', value: 'last_day_of_month' },
        { id: 4, label: 'First day of year', value: 'first_day_of_year' },
        { id: 5, label: 'Last day of year', value: 'last_day_of_year' },
        { id: 6, label: 'Payroll lock', value: 'payroll_lock' },
    ],
    leaveOperators: [
        { id: 1, label: '=', value: '=' },
        { id: 2, label: '>=', value: '>=' },
        { id: 3, label: '<=', value: '<=' },
    ],
    leaveType: [
        { id: 1, label: 'Paid', value: 'paid' },
        { id: 2, label: 'Unpaid', value: 'unpaid' },
        { id: 3, label: 'On duty', value: 'on_duty' },
    ],
    leaveBalanceBasedOn: [
        { id: 1, label: 'Fixed entitlement', value: 'fixed_entitlement' },
        { id: 2, label: 'Grant leave', value: 'grant_leave' },
    ],
    leaveEffectiveAfterName: [
        { id: 1, label: 'Day', value: 'day' },
        { id: 2, label: 'Month', value: 'month' },
        { id: 3, label: 'Year', value: 'year' },
    ],
    leaveEffectiveAfterValue: [
        { id: 1, label: 'Date of joining', value: 'date_of_joining' },
        { id: 2, label: 'Date of confirmation', value: 'date_of_confirmation' },
    ],
    exceedLeaveBalanceValue: [
        { id: 1, label: 'Without limit', value: 'without_limit' },
        { id: 2, label: 'Year end limit', value: 'year_end_limit' },
        { id: 3, label: 'Without limit as lwp', value: 'without_limit_as_lwp' },
    ],
    leaveAllowRequestsFor: [
        { id: 1, label: 'Past date', value: 'past_date' },
        { id: 2, label: 'Future date', value: 'future_date' },
        { id: 3, label: 'Both', value: 'both' },
    ],
    brackets: [
        { id: 1, label: '(', value: '(' },
        { id: 2, label: '{', value: '{' },
        { id: 3, label: '[', value: '[' },
    ],
    abbreviations: [
        { id: 1, label: 'BASIC', value: 'BASIC' },
        { id: 2, label: 'HRA', value: 'HRA' },
        { id: 3, label: 'CTC', value: 'CTC' },
        { id: 4, label: 'PL', value: 'PL' },
        { id: 5, label: 'EL', value: 'EL' },
    ],
    operators: [
        { id: 1, label: '+', value: '+' },
        { id: 2, label: '-', value: '-' },
        { id: 3, label: '*', value: '*' },
        { id: 4, label: '/', value: '/' },
        { id: 5, label: '%', value: '%' },
        { id: 6, label: ')', value: ')' },
        { id: 7, label: '}', value: '}' },
        { id: 8, label: ']', value: ']' },
    ],
    attendanceTrackingType: [
        { id: 1, label: 'Present Absent', value: 'present_absent' },
        { id: 2, label: 'Punch-In / Punch-Out Time', value: 'punchInTime_punchOutTime' },

    ],

}

const autoIncrementId = {
    start: 10001,
}

const dropdownMasters = {
    dropdownCategory: [
        { id: 1, label: 'Skills', value: 'skills' },
        { id: 2, label: 'Source', value: 'source' },
        { id: 3, label: 'Year of experience', value: 'year_of_experience' },
        { id: 4, label: 'Interview stage', value: 'interview_stage' },
        { id: 5, label: 'Interview Type', value: 'interview_type' },
        { id: 6, label: 'Priority', value: 'priority' },
        { id: 7, label: 'Business impact', value: 'business_impact' },
        { id: 8, label: 'Payment type', value: 'payment_type' },
        { id: 9, label: 'Learning development cost', value: 'learning_development_cost' },
        { id: 10, label: 'Type of Appointment', value: 'type_of_appointment' },
        { id: 11, label: 'Loan Type', value: 'loan_type' },
        { id: 12, label: 'EMI Duration', value: 'emi_duration' },
        { id: 13, label: 'Travel Class Type ', value: 'travel_class_type' },
        { id: 14, label: 'Car Type ', value: 'car_type' },
        { id: 15, label: 'Travel Category', value: 'travel_category' },
        { id: 16, label: 'Flight Class', value: 'flight_class' },
    ],
    dropdownInputType: [
        { id: 1, label: 'Text', value: 'text' },
        { id: 2, label: 'Number', value: 'number' },
        { id: 3, label: 'Date', value: 'date' },
        { id: 4, label: 'Checkbox', value: 'checkbox' },
        { id: 4, label: 'Radio', value: 'radio' },
        { id: 5, label: 'Tel', value: 'tel' },
        { id: 5, label: 'Dropdown', value: 'dropdown' },
    ],
}

const shortLeaveConstants = {
    shortLeaveUsedAs: [
        { id: 1, label: 'Attendance calculation', value: 'attendance_calculation' },
        { id: 2, label: 'Apply leave', value: 'apply_leave' },
    ],
    shortLeaveApplicableWithin: [
        { id: 1, label: 'Week', value: 'week' },
        { id: 2, label: 'Month', value: 'month' },
    ],
    shortLeaveApplicableFor: [
        { id: 1, label: 'All', value: 'all' },
        { id: 2, label: 'Specific', value: 'specific' },
    ]
}

const woStatus = ['WO', 'WO_P', 'WO_FHP', 'WO_SHP', 'PH', 'PH_P', 'PH_FHP', 'PH_SHP'];

const permissionConstant = {
    permissionType: [
        { id: 1, label: 'Menu', value: 'menu' },
        { id: 2, label: 'Submenu', value: 'submenu' },
        { id: 3, label: 'Route', value: 'route' },
    ],
    category: [
        { id: 1, label: 'Permission', value: 'permission' },
        { id: 2, label: 'Department', value: 'department' },
        { id: 3, label: 'Designation', value: 'designation' },
        { id: 4, label: 'Position', value: 'position' },
        { id: 5, label: 'Admin', value: 'admin' },
        { id: 7, label: 'Hiring', value: 'hiring' },
        { id: 8, label: 'Attendance', value: 'attendance' },
        { id: 9, label: 'payroll Admin', value: 'payroll_admin' },
        { id: 10, label: 'Travel & Claim', value: 'travel_and_claim' },
        { id: 11, label: 'Performance Management', value: 'pms' },
        { id: 12, label: 'Community', value: 'community' },
        { id: 12, label: 'Route', value: 'route' },
         { id: 12, label: 'Task Management', value: 'task_management' },

    ]
};

const leaveEncashmentConstant = ['BASIC', 'HRA', 'CTC', 'PL', 'EL'];

const approvalHierarchyConstant = {
    type: [
        { id: 1, label: 'Mrf', value: 'mrf' },
        { id: 2, label: 'Leave', value: 'leave' },
        { id: 3, label: 'Attendance Correction', value: 'attendance_correction' },
        { id: 4, label: 'Comp Off', value: 'comp_off' },
        { id: 5, label: 'tour', value: 'tour' },
        { id: 6, label: 'travel', value: 'travel' },
        { id: 7, label: 'advance', value: 'advance' },
        { id: 8, label: 'Claim', value: 'claim' },
        { id: 8, label: 'Kudos', value: 'kudos' },

    ],
    approvalLevel: [
        { id: 1, label: 'Single', value: 'single' },
        { id: 2, label: 'Multiple', value: 'multiple' },
    ]
};
const sampleHolidayData = [
    {
        name: 'holiday testing',
        description: 'testing holiday 123',
        gender: 'Female',
        country: 'India',
        state: 'Rajasthan',
        city: 'Jaipur',
        branch: 'Branch Office',
        restricted: true,
        notify_before_days: 0,
        is_notify_to_employee: false,
        is_reprocess_leave: false,
        date: 45606,
        apply_for: 'First Day',
        holiday_start_date: 45606,
        holiday_end_date: 45611
    }]

const styles = {
        present: { color: " #44C4A1", background: "rgba(68, 196, 161, .15)", borderLeftColor: " #44C4A1",img:"present-icon.svg" },
        absent: { color: " #E12D20", background: "rgba(225, 45, 32, .07)", borderLeftColor: " #E12D20",img:"absent-icon.svg" },
        weekOff: { color: " #212529", background: " #f5f5f5", borderLeftColor: " #212529",img:"weekoff-icon.svg" },
        holiday: { color: " #2B7B8A", background: "rgba(43, 123, 138, .1)", borderLeftColor: "  #2B7B8A",img:"ph-icon.svg" },
        leave:{ color: "#00376A", background: "rgba(40, 87, 131, 0.1)", borderLeftColor: "#2B7B8A",img:"pl-icon.svg"},
        default:{color:" #00376a", background: " #00376a1a", borderLeftColor: " #00376a" ,img:"pl-icon.svg"}
};

const checkAttendanceWithAllStatus = {
    "PR": [{ status: "Full Day Present", style: styles.present }],
    "AB": [{ status: "Full Day Absent", style: styles.absent }],
    "WO": [{ status: "Week Off", style: styles.weekOff }],
    "WO_P": [{ status: "Week Off Present", style: styles.present }],
    "WO_FHP": [
        { status: "1st Half Week Off Present", style: styles.present },
        { status: "Week Off", style: styles.weekOff }
    ],
    "WO_SHP": [
        { status: "Week Off", style: styles.weekOff },
        { status: "2nd Half Week Off Present", style: styles.present }
    ],
    "FHP": [
        { status: "1st Half Present", style: styles.present },
        { status: "2nd Half Absent", style: styles.absent }
    ],
    "SHP": [
        { status: "1st Half Absent", style: styles.absent },
        { status: "2nd Half Present", style: styles.present }
    ],
    "FH_SSL": [
        { status: "1st Half Short Leave", style: styles.absent },
        { status: "2nd Half Present", style: styles.present }
    ],
    "SH_SSL": [
        { status: "1st Half Present", style: styles.present },
        { status: "2nd Half Short Leave", style: styles.absent }
    ],
    "PH": [{ status: "Public Holiday", style: styles.holiday }],
    "FH_PH": [
        { status: "1st Half Holiday Present", style: styles.present },
        { status: "Public Holiday", style: styles.holiday }
    ],
    "SH_PH": [
        { status: "Public Holiday", style: styles.holiday },
        { status: "2nd Half Holiday Present", style: styles.present }
    ]
};

const ipWiseDoorInfo = {
    // new IP (9 May 2024)
    '192.168.3.10': 'Main Gate IN',
    '192.168.3.11': 'Main Gate OUT',
    '192.168.3.16': 'Cafe IN',
    '192.168.3.17': 'Cafe OUT',
    '192.168.3.12': 'Mini 1 IN',
    '192.168.3.13': 'Mini 1 OUT',
    '192.168.3.14': 'Mini 2 IN',
    '192.168.3.15': 'Mini 2 OUT',
    //old IP 
    '192.168.14.15': 'Main Gate IN',
    '192.168.14.16': 'Main Gate OUT',
    '192.168.14.17': 'Cafe IN',
    '192.168.14.18': 'Cafe OUT',
    '192.168.14.11': 'Mini 1 IN',
    '192.168.14.12': 'Mini 1 OUT',
    '192.168.14.13': 'Mini 2 IN',
    '192.168.14.14': 'Mini 2 OUT',
    //
    '192.168.5.18': 'Main Gate IN',
    '192.168.5.19': 'Main Gate OUT',
    '192.168.5.21': 'Cafe OUT',
    '192.168.5.20': 'Cafe IN',
    // pune office ip
    '192.168.9.5': 'Main Gate IN',
    '192.168.9.6': 'Main Gate OUT',
    '192.168.9.7': 'Training IN',
    '192.168.9.8': 'Training OUT',
  }

  const validationMessage = {

  }
 

  const adminDropDown = {
   countries : [
    { id: 1, name: "Afghanistan" },
    { id: 2, name: "Albania" },
    { id: 3, name: "Algeria" },
    { id: 4, name: "American Samoa" },
    { id: 5, name: "Angola" },
    { id: 6, name: "Anguilla" },
    { id: 8, name: "Antigua and Barbuda" },
    { id: 9, name: "Argentina" },
    { id: 10, name: "Armenia" },
    { id: 11, name: "Aruba" },
    { id: 13, name: "Australia" },
    { id: 14, name: "Austria" },
    { id: 15, name: "Azerbaijan" },
    { id: 16, name: "Bahamas" },
    { id: 17, name: "Bahrain" },
    { id: 18, name: "Bangladesh" },
    { id: 19, name: "Barbados" },
    { id: 20, name: "Belarus" },
    { id: 21, name: "Belgium" },
    { id: 22, name: "Belize" },
    { id: 23, name: "Benin" },
    { id: 24, name: "Bermuda" },
    { id: 25, name: "Bhutan" },
    { id: 26, name: "Bolivia" },
    { id: 27, name: "Bosnia and Herzegovina" },
    { id: 28, name: "Botswana" },
    { id: 30, name: "Brazil" },
    { id: 32, name: "British Virgin Islands" },
    { id: 33, name: "Brunei" },
    { id: 34, name: "Bulgaria" },
    { id: 35, name: "Burkina Faso" },
    { id: 37, name: "Burundi" },
    { id: 38, name: "Cambodia" },
    { id: 39, name: "Cameroon" },
    { id: 40, name: "Canada" },
    { id: 41, name: "Cape Verde" },
    { id: 42, name: "Cayman Islands" },
    { id: 43, name: "Central African Republic" },
    { id: 44, name: "Chad" },
    { id: 45, name: "Chile" },
    { id: 46, name: "China" },
    { id: 47, name: "Christmas Island" },
    { id: 49, name: "Cocos (Keeling) Islands" },
    { id: 50, name: "Colombia" },
    { id: 51, name: "Comoros" },
    { id: 52, name: "Congo" },
    { id: 53, name: "Cook Islands" },
    { id: 54, name: "Costa Rica" },
    { id: 56, name: "Croatia" },
    { id: 57, name: "Cuba" },
    { id: 59, name: "Cyprus" },
    { id: 61, name: "Denmark" },
    { id: 62, name: "Djibouti" },
    { id: 63, name: "Dominica" },
    { id: 64, name: "Dominican Republic" },
    { id: 65, name: "Ecuador" },
    { id: 66, name: "Egypt" },
    { id: 67, name: "El Salvador" },
    { id: 68, name: "United Kingdom" },
    { id: 69, name: "Equatorial Guinea" },
    { id: 70, name: "Eritrea" },
    { id: 71, name: "Estonia" },
    { id: 72, name: "Ethiopia" },
    { id: 75, name: "Faroe Islands" },
    { id: 76, name: "Fiji" },
    { id: 77, name: "Finland" },
    { id: 78, name: "France" },
    { id: 79, name: "French Guiana" },
    { id: 80, name: "French Polynesia" },
    { id: 82, name: "Gabon" },
    { id: 83, name: "Gambia" },
    { id: 85, name: "Georgia" },
    { id: 86, name: "Germany" },
    { id: 87, name: "Ghana" },
    { id: 88, name: "Gibraltar" },
    { id: 90, name: "Greece" },
    { id: 91, name: "Greenland" },
    { id: 92, name: "Grenada" },
    { id: 93, name: "Guadeloupe" },
    { id: 94, name: "Guam" },
    { id: 95, name: "Guatemala" },
    { id: 96, name: "Guernsey" },
    { id: 97, name: "Guinea" },
    { id: 98, name: "Guinea-Bissau" },
    { id: 99, name: "Guyana" },
    { id: 100, name: "Haiti" },
    { id: 101, name: "Heard Island and McDonald Islands" },
    { id: 103, name: "Honduras" },
    { id: 104, name: "Hong Kong" },
    { id: 106, name: "Hungary" },
    { id: 107, name: "Iceland" },
    { id: 108, name: "India" },
    { id: 109, name: "Indonesia" },
    { id: 110, name: "Iran" },
    { id: 111, name: "Iraq" },
    { id: 113, name: "Israel" },
    { id: 114, name: "Italy" },
    { id: 115, name: "Jamaica" },
    { id: 117, name: "Japan" },
    { id: 119, name: "Jersey" },
    { id: 121, name: "Jordan" },
    { id: 123, name: "Kazakhstan" },
    { id: 124, name: "Kenya" },
    { id: 125, name: "Kiribati" },
    { id: 126, name: "Korea" },
    { id: 128, name: "Kuwait" },
    { id: 129, name: "Kyrgyzstan" },
    { id: 130, name: "Laos" },
    { id: 131, name: "Latvia" },
    { id: 132, name: "Lebanon" },
    { id: 134, name: "Lesotho" },
    { id: 135, name: "Liberia" },
    { id: 136, name: "Libya" },
    { id: 137, name: "Liechtenstein" },
    { id: 139, name: "Lithuania" },
    { id: 140, name: "Luxembourg" },
    { id: 141, name: "Macau" },
    { id: 142, name: "Macedonia" },
    { id: 143, name: "Madagascar" },
    { id: 144, name: "Malawi" },
    { id: 145, name: "Malaysia" },
    { id: 146, name: "Maldives" },
    { id: 147, name: "Mali" },
    { id: 148, name: "Malta" },
    { id: 149, name: "Marshall Islands" },
    { id: 150, name: "Martinique" },
    { id: 151, name: "Mauritania" },
    { id: 152, name: "Mauritius" },
    { id: 153, name: "Mayotte" },
    { id: 154, name: "Mexico" },
    { id: 155, name: "Micronesia" },
    { id: 157, name: "Moldova" },
    { id: 158, name: "Monaco" },
    { id: 159, name: "Mongolia" },
    { id: 160, name: "Montserrat" },
    { id: 161, name: "Morocco" },
    { id: 162, name: "Mozambique" },
    { id: 163, name: "Namibia" },
    { id: 164, name: "Nauru" },
    { id: 165, name: "Nepal" },
    { id: 166, name: "Netherlands" },
    { id: 168, name: "New Caledonia" },
    { id: 169, name: "New Zealand" },
    { id: 171, name: "Nicaragua" },
    { id: 172, name: "Niger" },
    { id: 173, name: "Nigeria" },
    { id: 174, name: "Niue" },
    { id: 175, name: "Norfolk Island" },
    { id: 176, name: "Northern Mariana Islands" },
    { id: 177, name: "Norway" },
    { id: 178, name: "Oman" },
    { id: 179, name: "Pakistan" },
    { id: 180, name: "Palau" },
    { id: 181, name: "Panama" },
    { id: 182, name: "Papua New Guinea" },
    { id: 183, name: "Paraguay" },
    { id: 184, name: "Peru" },
    { id: 185, name: "Philippines" },
    { id: 188, name: "Poland" },
    { id: 190, name: "Portugal" },
    { id: 191, name: "Puerto Rico" },
    { id: 192, name: "Qatar" },
    { id: 193, name: "Reunion" },
    { id: 195, name: "Russia" },
    { id: 196, name: "Rwanda" },
    { id: 198, name: "Saint Kitts and Nevis" },
    { id: 199, name: "Saint Lucia" },
    { id: 200, name: "Saint Pierre and Miquelon" },
    { id: 201, name: "Saint Vincent and the Grenadines" },
    { id: 202, name: "Samoa" },
    { id: 203, name: "San Marino" },
    { id: 205, name: "Sao Tome and Principe" },
    { id: 206, name: "Saudi Arabia" },
    { id: 208, name: "Senegal" },
    { id: 209, name: "Seychelles" },
    { id: 210, name: "Sierra Leone" },
    { id: 211, name: "Singapore" },
    { id: 212, name: "Slovakia" },
    { id: 213, name: "Slovenia" },
    { id: 214, name: "Solomon Islands" },
    { id: 215, name: "Somalia" },
    { id: 216, name: "South Africa" },
    { id: 218, name: "Spain" },
    { id: 220, name: "Sri Lanka" },
    { id: 221, name: "Sudan" },
    { id: 222, name: "Suriname" },
    { id: 224, name: "Swaziland" },
    { id: 225, name: "Sweden" },
    { id: 226, name: "Switzerland" },
    { id: 227, name: "Syria" },
    { id: 228, name: "Taiwan" },
    { id: 229, name: "Tajikistan" },
    { id: 230, name: "Tanzania" },
    { id: 231, name: "Thailand" },
    { id: 234, name: "Tokelau" },
    { id: 235, name: "Tonga" },
    { id: 237, name: "Tunisia" },
    { id: 238, name: "Turkey" },
    { id: 239, name: "Turkmenistan" },
    { id: 240, name: "Tuvalu" },
    { id: 241, name: "Uganda" },
    { id: 242, name: "Ukraine" },
    { id: 243, name: "United Arab Emirates" },
    { id: 244, name: "United States" },
    { id: 245, name: "Uruguay" },
    { id: 246, name: "Uzbekistan" },
    { id: 247, name: "Vanuatu" },
    { id: 248, name: "Venezuela" },
    { id: 249, name: "Vietnam" },
    { id: 252, name: "Wallis and Futuna" },
    { id: 254, name: "Western Sahara" },
    { id: 255, name: "Yemen" },
    { id: 257, name: "Zambia" },
    { id: 258, name: "Zimbabwe" }
  ],
  industryTypes: [
    { id: "16", name: "Aerospace & Defense" },
    { id: "12", name: "Agriculture & Food Processing" },
    { id: "8", name: "Automotive" },
    { id: "7", name: "Construction & Real Estate" },
    { id: "19", name: "Consulting" },
    { id: "4", name: "Education & E-Learning" },
    { id: "13", name: "Energy & Utilities" },
    { id: "2", name: "Financial Services" },
    { id: "14", name: "Government & Public Sector" },
    { id: "3", name: "Healthcare & Pharmaceuticals" },
    { id: "1", name: "Information Technology & Services" },
    { id: "17", name: "Legal Services" },
    { id: "15", name: "Logistics & Transportation" },
    { id: "6", name: "Manufacturing" },
    { id: "18", name: "Marketing & Advertising" },
    { id: "10", name: "Media & Entertainment" },
    { id: "5", name: "Retail & E-commerce" },
    { id: "11", name: "Telecommunications" },
    { id: "9", name: "Travel & Hospitality" }
  ],
  employeeRanges:[
    { id: "1_10", name: "1 - 10 Employees" },
    { id: "11_50", name: "11 - 50 Employees" },
    { id: "51_100", name: "51 - 100 Employees" },
    { id: "101_250", name: "101 - 250 Employees" },
    { id: "251_500", name: "251 - 500 Employees" },
    { id: "501_1000", name: "501 - 1,000 Employees" },
    { id: "1001_5000", name: "1,001 - 5,000 Employees" },
    { id: "5001_10000", name: "5,001 - 10,000 Employees" },
    { id: "10000_plus", name: "10,000+ Employees" }
  ],
  timeZones : [
    { id: "Asia/Kolkata", name: "(GMT+05:30) Asia/Kolkata" },
    { id: "America/New_York", name: "(GMT-05:00) America/New_York" },
    { id: "America/Los_Angeles", name: "(GMT-08:00) America/Los_Angeles" },
    { id: "Europe/London", name: "(GMT+00:00) Europe/London" },
    { id: "Europe/Berlin", name: "(GMT+01:00) Europe/Berlin" },
    { id: "Asia/Tokyo", name: "(GMT+09:00) Asia/Tokyo" },
    { id: "Australia/Sydney", name: "(GMT+10:00) Australia/Sydney" },
    { id: "Africa/Nairobi", name: "(GMT+03:00) Africa/Nairobi" },
    { id: "America/Sao_Paulo", name: "(GMT-03:00) America/Sao_Paulo" },
    { id: "Asia/Dubai", name: "(GMT+04:00) Asia/Dubai" }
  ]

}
  



module.exports = {
    messages,
    otpExpiresIn,
    appConstants,
    autoIncrementId,
    leaveConstants,
    dropdownMasters,
    shortLeaveConstants,
    woStatus,
    permissionConstant,
    leaveEncashmentConstant,
    approvalHierarchyConstant,
    sampleHolidayData,
    checkAttendanceWithAllStatus,
    styles,
    ipWiseDoorInfo,
    validationMessage,
    adminDropDown
}